---
name: terratest

on:
  workflow_call:
    inputs:
      work_dir:
        description: name of the directory where the action is located
        required: true
        type: string
        default: ./terratest-action
      test:
        description: name of the test to run e.g. azure
        type: string
        required: true
      debug:
        description: should debug mode be enabled
        required: false
        type: string
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true

      - name: Prepare Test Setup
        run: cat examples/min_main.tf | sed 's/\<source\>.*/source = "..\/"/g' > tests/main.tf
        working-directory: .

      - name: Checkout Github Action
        uses: actions/checkout@v3
        with:
          repository: T-Systems-MMS/terratest-action
          ref: main
          path: ./terratest-action

      - name: Run Test
        uses: ./terratest-action
        with:
          work_dir: ${{ inputs.work_dir }}
          test: ${{ inputs.test }}
          debug: ${{ inputs.debug }}
